[tasks.build]
command = "cargo"
args = ["build", "--all-features"]

[tasks.release]
command = "cargo"
dependencies = ["update"]
args = ["build", "--frozen", "--all-features", "--release"]

[tasks.fixfmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fixclippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features", "--fix"]

[tasks.releasecheck]
dependencies = ["fixclippy", "fixfmt", "update"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.publish]
dependencies = ["releasecheck"]
command = "cargo"
args = ["publish"]

[tasks.publishdry]
extend = "publish"
args = ["publish", "--dry-run"]

[tasks.clippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features"]